(cl:defpackage kr_mav_msgs-msg
  (:use )
  (:export
   "<AUXCOMMAND>"
   "AUXCOMMAND"
   "<CORRECTIONS>"
   "CORRECTIONS"
   "<MOTORRPM>"
   "MOTORRPM"
   "<OUTPUTDATA>"
   "OUTPUTDATA"
   "<PWMCOMMAND>"
   "PWMCOMMAND"
   "<POSITIONCOMMAND>"
   "POSITIONCOMMAND"
   "<SO3COMMAND>"
   "SO3COMMAND"
   "<SERIAL>"
   "SERIAL"
   "<STATUSDATA>"
   "STATUSDATA"
   "<TRPYCOMMAND>"
   "TRPYCOMMAND"
  ))

