// Generated by gencpp from file kr_mav_manager/LissajousRequest.msg
// DO NOT EDIT!


#ifndef KR_MAV_MANAGER_MESSAGE_LISSAJOUSREQUEST_H
#define KR_MAV_MANAGER_MESSAGE_LISSAJOUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kr_mav_manager
{
template <class ContainerAllocator>
struct LissajousRequest_
{
  typedef LissajousRequest_<ContainerAllocator> Type;

  LissajousRequest_()
    : x_amp(0.0)
    , y_amp(0.0)
    , z_amp(0.0)
    , yaw_amp(0.0)
    , x_num_periods(0.0)
    , y_num_periods(0.0)
    , z_num_periods(0.0)
    , yaw_num_periods(0.0)
    , period(0.0)
    , num_cycles(0.0)
    , ramp_time(0.0)  {
    }
  LissajousRequest_(const ContainerAllocator& _alloc)
    : x_amp(0.0)
    , y_amp(0.0)
    , z_amp(0.0)
    , yaw_amp(0.0)
    , x_num_periods(0.0)
    , y_num_periods(0.0)
    , z_num_periods(0.0)
    , yaw_num_periods(0.0)
    , period(0.0)
    , num_cycles(0.0)
    , ramp_time(0.0)  {
  (void)_alloc;
    }



   typedef float _x_amp_type;
  _x_amp_type x_amp;

   typedef float _y_amp_type;
  _y_amp_type y_amp;

   typedef float _z_amp_type;
  _z_amp_type z_amp;

   typedef float _yaw_amp_type;
  _yaw_amp_type yaw_amp;

   typedef float _x_num_periods_type;
  _x_num_periods_type x_num_periods;

   typedef float _y_num_periods_type;
  _y_num_periods_type y_num_periods;

   typedef float _z_num_periods_type;
  _z_num_periods_type z_num_periods;

   typedef float _yaw_num_periods_type;
  _yaw_num_periods_type yaw_num_periods;

   typedef float _period_type;
  _period_type period;

   typedef float _num_cycles_type;
  _num_cycles_type num_cycles;

   typedef float _ramp_time_type;
  _ramp_time_type ramp_time;





  typedef boost::shared_ptr< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LissajousRequest_

typedef ::kr_mav_manager::LissajousRequest_<std::allocator<void> > LissajousRequest;

typedef boost::shared_ptr< ::kr_mav_manager::LissajousRequest > LissajousRequestPtr;
typedef boost::shared_ptr< ::kr_mav_manager::LissajousRequest const> LissajousRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kr_mav_manager::LissajousRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kr_mav_manager::LissajousRequest_<ContainerAllocator1> & lhs, const ::kr_mav_manager::LissajousRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x_amp == rhs.x_amp &&
    lhs.y_amp == rhs.y_amp &&
    lhs.z_amp == rhs.z_amp &&
    lhs.yaw_amp == rhs.yaw_amp &&
    lhs.x_num_periods == rhs.x_num_periods &&
    lhs.y_num_periods == rhs.y_num_periods &&
    lhs.z_num_periods == rhs.z_num_periods &&
    lhs.yaw_num_periods == rhs.yaw_num_periods &&
    lhs.period == rhs.period &&
    lhs.num_cycles == rhs.num_cycles &&
    lhs.ramp_time == rhs.ramp_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kr_mav_manager::LissajousRequest_<ContainerAllocator1> & lhs, const ::kr_mav_manager::LissajousRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kr_mav_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c943e68ce1a4a9f23725880ddfca8fa9";
  }

  static const char* value(const ::kr_mav_manager::LissajousRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc943e68ce1a4a9f2ULL;
  static const uint64_t static_value2 = 0x3725880ddfca8fa9ULL;
};

template<class ContainerAllocator>
struct DataType< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kr_mav_manager/LissajousRequest";
  }

  static const char* value(const ::kr_mav_manager::LissajousRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x_amp\n"
"float32 y_amp\n"
"float32 z_amp\n"
"float32 yaw_amp\n"
"float32 x_num_periods\n"
"float32 y_num_periods\n"
"float32 z_num_periods\n"
"float32 yaw_num_periods\n"
"float32 period\n"
"float32 num_cycles\n"
"float32 ramp_time\n"
;
  }

  static const char* value(const ::kr_mav_manager::LissajousRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_amp);
      stream.next(m.y_amp);
      stream.next(m.z_amp);
      stream.next(m.yaw_amp);
      stream.next(m.x_num_periods);
      stream.next(m.y_num_periods);
      stream.next(m.z_num_periods);
      stream.next(m.yaw_num_periods);
      stream.next(m.period);
      stream.next(m.num_cycles);
      stream.next(m.ramp_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LissajousRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kr_mav_manager::LissajousRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kr_mav_manager::LissajousRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_amp: ";
    Printer<float>::stream(s, indent + "  ", v.x_amp);
    s << indent << "y_amp: ";
    Printer<float>::stream(s, indent + "  ", v.y_amp);
    s << indent << "z_amp: ";
    Printer<float>::stream(s, indent + "  ", v.z_amp);
    s << indent << "yaw_amp: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_amp);
    s << indent << "x_num_periods: ";
    Printer<float>::stream(s, indent + "  ", v.x_num_periods);
    s << indent << "y_num_periods: ";
    Printer<float>::stream(s, indent + "  ", v.y_num_periods);
    s << indent << "z_num_periods: ";
    Printer<float>::stream(s, indent + "  ", v.z_num_periods);
    s << indent << "yaw_num_periods: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_num_periods);
    s << indent << "period: ";
    Printer<float>::stream(s, indent + "  ", v.period);
    s << indent << "num_cycles: ";
    Printer<float>::stream(s, indent + "  ", v.num_cycles);
    s << indent << "ramp_time: ";
    Printer<float>::stream(s, indent + "  ", v.ramp_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KR_MAV_MANAGER_MESSAGE_LISSAJOUSREQUEST_H
