#Accelerometers
accelerometer_noise_density: 4.00e-03 #Noise density (continuous-time)
accelerometer_random_walk: 8.00e-04 #Bias random walk

#Gyroscopes
gyroscope_noise_density: 1.0e-03 #Noise density (continuous-time)
gyroscope_random_walk: 2.0e-04 #Bias random walk

rostopic: imu #the IMU ROS topic
update_rate: 100.0 #Hz (for discretization of the values above)
