// Auto-generated. Do not edit!

// (in-package kr_tracker_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CircleTrackerGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.Ax = null;
      this.Ay = null;
      this.T = null;
      this.duration = null;
    }
    else {
      if (initObj.hasOwnProperty('Ax')) {
        this.Ax = initObj.Ax
      }
      else {
        this.Ax = 0.0;
      }
      if (initObj.hasOwnProperty('Ay')) {
        this.Ay = initObj.Ay
      }
      else {
        this.Ay = 0.0;
      }
      if (initObj.hasOwnProperty('T')) {
        this.T = initObj.T
      }
      else {
        this.T = 0.0;
      }
      if (initObj.hasOwnProperty('duration')) {
        this.duration = initObj.duration
      }
      else {
        this.duration = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CircleTrackerGoal
    // Serialize message field [Ax]
    bufferOffset = _serializer.float64(obj.Ax, buffer, bufferOffset);
    // Serialize message field [Ay]
    bufferOffset = _serializer.float64(obj.Ay, buffer, bufferOffset);
    // Serialize message field [T]
    bufferOffset = _serializer.float64(obj.T, buffer, bufferOffset);
    // Serialize message field [duration]
    bufferOffset = _serializer.float64(obj.duration, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CircleTrackerGoal
    let len;
    let data = new CircleTrackerGoal(null);
    // Deserialize message field [Ax]
    data.Ax = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [Ay]
    data.Ay = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [T]
    data.T = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [duration]
    data.duration = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 32;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kr_tracker_msgs/CircleTrackerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a8f8072fad05d8c7a0d620729ddae035';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float64 Ax
    float64 Ay
    float64 T
    float64 duration
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CircleTrackerGoal(null);
    if (msg.Ax !== undefined) {
      resolved.Ax = msg.Ax;
    }
    else {
      resolved.Ax = 0.0
    }

    if (msg.Ay !== undefined) {
      resolved.Ay = msg.Ay;
    }
    else {
      resolved.Ay = 0.0
    }

    if (msg.T !== undefined) {
      resolved.T = msg.T;
    }
    else {
      resolved.T = 0.0
    }

    if (msg.duration !== undefined) {
      resolved.duration = msg.duration;
    }
    else {
      resolved.duration = 0.0
    }

    return resolved;
    }
};

module.exports = CircleTrackerGoal;
