// Auto-generated. Do not edit!

// (in-package kr_tracker_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let LissajousAdderActionGoal = require('./LissajousAdderActionGoal.js');
let LissajousAdderActionResult = require('./LissajousAdderActionResult.js');
let LissajousAdderActionFeedback = require('./LissajousAdderActionFeedback.js');

//-----------------------------------------------------------

class LissajousAdderAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new LissajousAdderActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new LissajousAdderActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new LissajousAdderActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LissajousAdderAction
    // Serialize message field [action_goal]
    bufferOffset = LissajousAdderActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = LissajousAdderActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = LissajousAdderActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LissajousAdderAction
    let len;
    let data = new LissajousAdderAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = LissajousAdderActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = LissajousAdderActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = LissajousAdderActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += LissajousAdderActionGoal.getMessageSize(object.action_goal);
    length += LissajousAdderActionResult.getMessageSize(object.action_result);
    length += LissajousAdderActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kr_tracker_msgs/LissajousAdderAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '518ad5daf050f120c7c518e9332e2220';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    LissajousAdderActionGoal action_goal
    LissajousAdderActionResult action_result
    LissajousAdderActionFeedback action_feedback
    
    ================================================================================
    MSG: kr_tracker_msgs/LissajousAdderActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    LissajousAdderGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: kr_tracker_msgs/LissajousAdderGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float64[2] x_amp
    float64[2] y_amp
    float64[2] z_amp
    float64[2] yaw_amp
    float64[2] x_num_periods
    float64[2] y_num_periods
    float64[2] z_num_periods
    float64[2] yaw_num_periods
    float64[2] period
    float64[2] num_cycles
    float64[2] ramp_time
    
    ================================================================================
    MSG: kr_tracker_msgs/LissajousAdderActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    LissajousAdderResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: kr_tracker_msgs/LissajousAdderResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    # send back goal
    float64 x
    float64 y
    float64 z
    float64 yaw
    # time duration of the trajectory
    float64 duration
    # approximate arc length of the trajectory (ie. sum of distances between position commands)
    float64 length
    
    ================================================================================
    MSG: kr_tracker_msgs/LissajousAdderActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    LissajousAdderFeedback feedback
    
    ================================================================================
    MSG: kr_tracker_msgs/LissajousAdderFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    # distance from the goal
    float64 time_to_completion
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LissajousAdderAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = LissajousAdderActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new LissajousAdderActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = LissajousAdderActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new LissajousAdderActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = LissajousAdderActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new LissajousAdderActionFeedback()
    }

    return resolved;
    }
};

module.exports = LissajousAdderAction;
