// Auto-generated. Do not edit!

// (in-package kr_tracker_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LissajousAdderFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.time_to_completion = null;
    }
    else {
      if (initObj.hasOwnProperty('time_to_completion')) {
        this.time_to_completion = initObj.time_to_completion
      }
      else {
        this.time_to_completion = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LissajousAdderFeedback
    // Serialize message field [time_to_completion]
    bufferOffset = _serializer.float64(obj.time_to_completion, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LissajousAdderFeedback
    let len;
    let data = new LissajousAdderFeedback(null);
    // Deserialize message field [time_to_completion]
    data.time_to_completion = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kr_tracker_msgs/LissajousAdderFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '214517dc2e3be6dd6dfc1aee81c582f8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    # distance from the goal
    float64 time_to_completion
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LissajousAdderFeedback(null);
    if (msg.time_to_completion !== undefined) {
      resolved.time_to_completion = msg.time_to_completion;
    }
    else {
      resolved.time_to_completion = 0.0
    }

    return resolved;
    }
};

module.exports = LissajousAdderFeedback;
