// Auto-generated. Do not edit!

// (in-package kr_tracker_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PolyTrackerResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_time = null;
      this.total_distance_travelled = null;
    }
    else {
      if (initObj.hasOwnProperty('total_time')) {
        this.total_time = initObj.total_time
      }
      else {
        this.total_time = 0.0;
      }
      if (initObj.hasOwnProperty('total_distance_travelled')) {
        this.total_distance_travelled = initObj.total_distance_travelled
      }
      else {
        this.total_distance_travelled = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PolyTrackerResult
    // Serialize message field [total_time]
    bufferOffset = _serializer.float64(obj.total_time, buffer, bufferOffset);
    // Serialize message field [total_distance_travelled]
    bufferOffset = _serializer.float64(obj.total_distance_travelled, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PolyTrackerResult
    let len;
    let data = new PolyTrackerResult(null);
    // Deserialize message field [total_time]
    data.total_time = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [total_distance_travelled]
    data.total_distance_travelled = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kr_tracker_msgs/PolyTrackerResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2d6eb504c212e951ae864626fb488daf';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float64 total_time
    float64 total_distance_travelled
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PolyTrackerResult(null);
    if (msg.total_time !== undefined) {
      resolved.total_time = msg.total_time;
    }
    else {
      resolved.total_time = 0.0
    }

    if (msg.total_distance_travelled !== undefined) {
      resolved.total_distance_travelled = msg.total_distance_travelled;
    }
    else {
      resolved.total_distance_travelled = 0.0
    }

    return resolved;
    }
};

module.exports = PolyTrackerResult;
