// Generated by gencpp from file kr_tracker_msgs/CircleTrackerGoal.msg
// DO NOT EDIT!


#ifndef KR_TRACKER_MSGS_MESSAGE_CIRCLETRACKERGOAL_H
#define KR_TRACKER_MSGS_MESSAGE_CIRCLETRACKERGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kr_tracker_msgs
{
template <class ContainerAllocator>
struct CircleTrackerGoal_
{
  typedef CircleTrackerGoal_<ContainerAllocator> Type;

  CircleTrackerGoal_()
    : Ax(0.0)
    , Ay(0.0)
    , T(0.0)
    , duration(0.0)  {
    }
  CircleTrackerGoal_(const ContainerAllocator& _alloc)
    : Ax(0.0)
    , Ay(0.0)
    , T(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef double _Ax_type;
  _Ax_type Ax;

   typedef double _Ay_type;
  _Ay_type Ay;

   typedef double _T_type;
  _T_type T;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CircleTrackerGoal_

typedef ::kr_tracker_msgs::CircleTrackerGoal_<std::allocator<void> > CircleTrackerGoal;

typedef boost::shared_ptr< ::kr_tracker_msgs::CircleTrackerGoal > CircleTrackerGoalPtr;
typedef boost::shared_ptr< ::kr_tracker_msgs::CircleTrackerGoal const> CircleTrackerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator1> & lhs, const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator2> & rhs)
{
  return lhs.Ax == rhs.Ax &&
    lhs.Ay == rhs.Ay &&
    lhs.T == rhs.T &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator1> & lhs, const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kr_tracker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8f8072fad05d8c7a0d620729ddae035";
  }

  static const char* value(const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8f8072fad05d8c7ULL;
  static const uint64_t static_value2 = 0xa0d620729ddae035ULL;
};

template<class ContainerAllocator>
struct DataType< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kr_tracker_msgs/CircleTrackerGoal";
  }

  static const char* value(const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"float64 Ax\n"
"float64 Ay\n"
"float64 T\n"
"float64 duration\n"
;
  }

  static const char* value(const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Ax);
      stream.next(m.Ay);
      stream.next(m.T);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircleTrackerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kr_tracker_msgs::CircleTrackerGoal_<ContainerAllocator>& v)
  {
    s << indent << "Ax: ";
    Printer<double>::stream(s, indent + "  ", v.Ax);
    s << indent << "Ay: ";
    Printer<double>::stream(s, indent + "  ", v.Ay);
    s << indent << "T: ";
    Printer<double>::stream(s, indent + "  ", v.T);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KR_TRACKER_MSGS_MESSAGE_CIRCLETRACKERGOAL_H
