// Generated by gencpp from file kr_tracker_msgs/LineTrackerFeedback.msg
// DO NOT EDIT!


#ifndef KR_TRACKER_MSGS_MESSAGE_LINETRACKERFEEDBACK_H
#define KR_TRACKER_MSGS_MESSAGE_LINETRACKERFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kr_tracker_msgs
{
template <class ContainerAllocator>
struct LineTrackerFeedback_
{
  typedef LineTrackerFeedback_<ContainerAllocator> Type;

  LineTrackerFeedback_()
    : distance_from_goal(0.0)  {
    }
  LineTrackerFeedback_(const ContainerAllocator& _alloc)
    : distance_from_goal(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_from_goal_type;
  _distance_from_goal_type distance_from_goal;





  typedef boost::shared_ptr< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LineTrackerFeedback_

typedef ::kr_tracker_msgs::LineTrackerFeedback_<std::allocator<void> > LineTrackerFeedback;

typedef boost::shared_ptr< ::kr_tracker_msgs::LineTrackerFeedback > LineTrackerFeedbackPtr;
typedef boost::shared_ptr< ::kr_tracker_msgs::LineTrackerFeedback const> LineTrackerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator1> & lhs, const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance_from_goal == rhs.distance_from_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator1> & lhs, const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kr_tracker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e91cbeef049b19df7ed0de3978957293";
  }

  static const char* value(const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe91cbeef049b19dfULL;
  static const uint64_t static_value2 = 0x7ed0de3978957293ULL;
};

template<class ContainerAllocator>
struct DataType< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kr_tracker_msgs/LineTrackerFeedback";
  }

  static const char* value(const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"# distance from the goal\n"
"float64 distance_from_goal\n"
"\n"
;
  }

  static const char* value(const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_from_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineTrackerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kr_tracker_msgs::LineTrackerFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance_from_goal: ";
    Printer<double>::stream(s, indent + "  ", v.distance_from_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KR_TRACKER_MSGS_MESSAGE_LINETRACKERFEEDBACK_H
