// Generated by gencpp from file kr_tracker_msgs/LissajousAdderFeedback.msg
// DO NOT EDIT!


#ifndef KR_TRACKER_MSGS_MESSAGE_LISSAJOUSADDERFEEDBACK_H
#define KR_TRACKER_MSGS_MESSAGE_LISSAJOUSADDERFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kr_tracker_msgs
{
template <class ContainerAllocator>
struct LissajousAdderFeedback_
{
  typedef LissajousAdderFeedback_<ContainerAllocator> Type;

  LissajousAdderFeedback_()
    : time_to_completion(0.0)  {
    }
  LissajousAdderFeedback_(const ContainerAllocator& _alloc)
    : time_to_completion(0.0)  {
  (void)_alloc;
    }



   typedef double _time_to_completion_type;
  _time_to_completion_type time_to_completion;





  typedef boost::shared_ptr< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LissajousAdderFeedback_

typedef ::kr_tracker_msgs::LissajousAdderFeedback_<std::allocator<void> > LissajousAdderFeedback;

typedef boost::shared_ptr< ::kr_tracker_msgs::LissajousAdderFeedback > LissajousAdderFeedbackPtr;
typedef boost::shared_ptr< ::kr_tracker_msgs::LissajousAdderFeedback const> LissajousAdderFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator1> & lhs, const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.time_to_completion == rhs.time_to_completion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator1> & lhs, const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kr_tracker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "214517dc2e3be6dd6dfc1aee81c582f8";
  }

  static const char* value(const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x214517dc2e3be6ddULL;
  static const uint64_t static_value2 = 0x6dfc1aee81c582f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kr_tracker_msgs/LissajousAdderFeedback";
  }

  static const char* value(const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"# distance from the goal\n"
"float64 time_to_completion\n"
"\n"
;
  }

  static const char* value(const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_to_completion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LissajousAdderFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kr_tracker_msgs::LissajousAdderFeedback_<ContainerAllocator>& v)
  {
    s << indent << "time_to_completion: ";
    Printer<double>::stream(s, indent + "  ", v.time_to_completion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KR_TRACKER_MSGS_MESSAGE_LISSAJOUSADDERFEEDBACK_H
