gains:
  pos: {x: 5.0, y: 5.0, z: 6.0}
  vel: {x: 2.4, y: 2.4, z: 6.7}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}

  ki:  {x: 0.00, y: 0.004, z: 0.03}
  kib: {x: 0.00, y: 0.00, z: 0.00}

corrections:
  kf: 0.0e-08
  r: 0.0
  p: 0.0

max_pos_int:   0.5
max_pos_int_b: 0.5
# gains:
#         #   pos: { x: 6.0, y: 6.0, z: 8.0 }
#         #   vel: { x: 3.0, y: 3.0, z: 3.5 }
#   pos: { x: 6.0, y: 6.0, z: 1.6 }
#   vel: { x: 3.0, y: 3.0, z: 0.7 }
#   ki: { x: 0.00, y: 0.00, z: 0.00 }
#   kib: { x: 0.00, y: 0.00, z: 0.00 }
#   rot: { x: 1.2, y: 1.2, z: 1.0 }
#   ang: { x: 0.13, y: 0.13, z: 0.1}
# 
# corrections:
#   kf: 0.0e-08
#   r: 0.0
#   p: 0.0
# 
# max_pos_int: 0.3
# max_pos_int_b: 0.3
