// Generated by gencpp from file kr_mav_msgs/PositionCommand.msg
// DO NOT EDIT!


#ifndef KR_MAV_MSGS_MESSAGE_POSITIONCOMMAND_H
#define KR_MAV_MSGS_MESSAGE_POSITIONCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace kr_mav_msgs
{
template <class ContainerAllocator>
struct PositionCommand_
{
  typedef PositionCommand_<ContainerAllocator> Type;

  PositionCommand_()
    : header()
    , position()
    , velocity()
    , acceleration()
    , jerk()
    , yaw(0.0)
    , yaw_dot(0.0)
    , kx()
    , kv()
    , use_msg_gains_flags(0)  {
      kx.assign(0.0);

      kv.assign(0.0);
  }
  PositionCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)
    , jerk(_alloc)
    , yaw(0.0)
    , yaw_dot(0.0)
    , kx()
    , kv()
    , use_msg_gains_flags(0)  {
  (void)_alloc;
      kx.assign(0.0);

      kv.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _jerk_type;
  _jerk_type jerk;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _yaw_dot_type;
  _yaw_dot_type yaw_dot;

   typedef boost::array<double, 3>  _kx_type;
  _kx_type kx;

   typedef boost::array<double, 3>  _kv_type;
  _kv_type kv;

   typedef uint8_t _use_msg_gains_flags_type;
  _use_msg_gains_flags_type use_msg_gains_flags;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(USE_MSG_GAINS_NONE)
  #undef USE_MSG_GAINS_NONE
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_POSITION_X)
  #undef USE_MSG_GAINS_POSITION_X
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_POSITION_Y)
  #undef USE_MSG_GAINS_POSITION_Y
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_POSITION_Z)
  #undef USE_MSG_GAINS_POSITION_Z
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_POSITION_ALL)
  #undef USE_MSG_GAINS_POSITION_ALL
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_VELOCITY_X)
  #undef USE_MSG_GAINS_VELOCITY_X
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_VELOCITY_Y)
  #undef USE_MSG_GAINS_VELOCITY_Y
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_VELOCITY_Z)
  #undef USE_MSG_GAINS_VELOCITY_Z
#endif
#if defined(_WIN32) && defined(USE_MSG_GAINS_VELOCITY_ALL)
  #undef USE_MSG_GAINS_VELOCITY_ALL
#endif

  enum {
    USE_MSG_GAINS_NONE = 0u,
    USE_MSG_GAINS_POSITION_X = 1u,
    USE_MSG_GAINS_POSITION_Y = 2u,
    USE_MSG_GAINS_POSITION_Z = 4u,
    USE_MSG_GAINS_POSITION_ALL = 7u,
    USE_MSG_GAINS_VELOCITY_X = 8u,
    USE_MSG_GAINS_VELOCITY_Y = 16u,
    USE_MSG_GAINS_VELOCITY_Z = 32u,
    USE_MSG_GAINS_VELOCITY_ALL = 56u,
  };


  typedef boost::shared_ptr< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> const> ConstPtr;

}; // struct PositionCommand_

typedef ::kr_mav_msgs::PositionCommand_<std::allocator<void> > PositionCommand;

typedef boost::shared_ptr< ::kr_mav_msgs::PositionCommand > PositionCommandPtr;
typedef boost::shared_ptr< ::kr_mav_msgs::PositionCommand const> PositionCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kr_mav_msgs::PositionCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kr_mav_msgs::PositionCommand_<ContainerAllocator1> & lhs, const ::kr_mav_msgs::PositionCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration &&
    lhs.jerk == rhs.jerk &&
    lhs.yaw == rhs.yaw &&
    lhs.yaw_dot == rhs.yaw_dot &&
    lhs.kx == rhs.kx &&
    lhs.kv == rhs.kv &&
    lhs.use_msg_gains_flags == rhs.use_msg_gains_flags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kr_mav_msgs::PositionCommand_<ContainerAllocator1> & lhs, const ::kr_mav_msgs::PositionCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kr_mav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0311a8eaed8b83c776def91b77632ae6";
  }

  static const char* value(const ::kr_mav_msgs::PositionCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0311a8eaed8b83c7ULL;
  static const uint64_t static_value2 = 0x76def91b77632ae6ULL;
};

template<class ContainerAllocator>
struct DataType< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kr_mav_msgs/PositionCommand";
  }

  static const char* value(const ::kr_mav_msgs::PositionCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 jerk\n"
"float64 yaw\n"
"float64 yaw_dot\n"
"float64[3] kx\n"
"float64[3] kv\n"
"\n"
"# use_msg_gains_flags: flags that can be set using the constants USE_MSG_GAINS_*\n"
"# to select which gains (kx, kv) from the message to use.  Note that by default\n"
"# the message gains are not used.\n"
"uint8 use_msg_gains_flags\n"
"\n"
"uint8 USE_MSG_GAINS_NONE         = 0\n"
"uint8 USE_MSG_GAINS_POSITION_X   = 1\n"
"uint8 USE_MSG_GAINS_POSITION_Y   = 2\n"
"uint8 USE_MSG_GAINS_POSITION_Z   = 4\n"
"uint8 USE_MSG_GAINS_POSITION_ALL = 7 # sets all three of the above\n"
"uint8 USE_MSG_GAINS_VELOCITY_X   = 8\n"
"uint8 USE_MSG_GAINS_VELOCITY_Y   = 16\n"
"uint8 USE_MSG_GAINS_VELOCITY_Z   = 32\n"
"uint8 USE_MSG_GAINS_VELOCITY_ALL = 56 # sets all three of the above\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::kr_mav_msgs::PositionCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.jerk);
      stream.next(m.yaw);
      stream.next(m.yaw_dot);
      stream.next(m.kx);
      stream.next(m.kv);
      stream.next(m.use_msg_gains_flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kr_mav_msgs::PositionCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kr_mav_msgs::PositionCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "jerk: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.jerk);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_dot: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_dot);
    s << indent << "kx[]" << std::endl;
    for (size_t i = 0; i < v.kx.size(); ++i)
    {
      s << indent << "  kx[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.kx[i]);
    }
    s << indent << "kv[]" << std::endl;
    for (size_t i = 0; i < v.kv.size(); ++i)
    {
      s << indent << "  kv[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.kv[i]);
    }
    s << indent << "use_msg_gains_flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_msg_gains_flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KR_MAV_MSGS_MESSAGE_POSITIONCOMMAND_H
