(cl:in-package kr_tracker_msgs-msg)
(cl:export '(T_START-VAL
          T_START
          ORDER-VAL
          ORDER
          SET_YAW-VAL
          SET_YAW
          SEPARATE_YAW-VAL
          SEPARATE_YAW
          START_YAW-VAL
          START_YAW
          FINAL_YAW-VAL
          FINAL_YAW
          SEG_X-VAL
          SEG_X
          SEG_Y-VAL
          SEG_Y
          SEG_Z-VAL
          SEG_Z
          SEG_YAW-VAL
          SEG_YAW
          CPTS_STATUS-VAL
          CPTS_STATUS
          POS_PTS-VAL
          POS_PTS
          YAW_PTS-VAL
          YAW_PTS
          KNOTS-VAL
          KNOTS
))