; Auto-generated. Do not edit!


(cl:in-package kr_tracker_msgs-msg)


;//! \htmlinclude LineTrackerFeedback.msg.html

(cl:defclass <LineTrackerFeedback> (roslisp-msg-protocol:ros-message)
  ((distance_from_goal
    :reader distance_from_goal
    :initarg :distance_from_goal
    :type cl:float
    :initform 0.0))
)

(cl:defclass LineTrackerFeedback (<LineTrackerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LineTrackerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LineTrackerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kr_tracker_msgs-msg:<LineTrackerFeedback> is deprecated: use kr_tracker_msgs-msg:LineTrackerFeedback instead.")))

(cl:ensure-generic-function 'distance_from_goal-val :lambda-list '(m))
(cl:defmethod distance_from_goal-val ((m <LineTrackerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kr_tracker_msgs-msg:distance_from_goal-val is deprecated.  Use kr_tracker_msgs-msg:distance_from_goal instead.")
  (distance_from_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LineTrackerFeedback>) ostream)
  "Serializes a message object of type '<LineTrackerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'distance_from_goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LineTrackerFeedback>) istream)
  "Deserializes a message object of type '<LineTrackerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance_from_goal) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LineTrackerFeedback>)))
  "Returns string type for a message object of type '<LineTrackerFeedback>"
  "kr_tracker_msgs/LineTrackerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LineTrackerFeedback)))
  "Returns string type for a message object of type 'LineTrackerFeedback"
  "kr_tracker_msgs/LineTrackerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LineTrackerFeedback>)))
  "Returns md5sum for a message object of type '<LineTrackerFeedback>"
  "e91cbeef049b19df7ed0de3978957293")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LineTrackerFeedback)))
  "Returns md5sum for a message object of type 'LineTrackerFeedback"
  "e91cbeef049b19df7ed0de3978957293")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LineTrackerFeedback>)))
  "Returns full string definition for message of type '<LineTrackerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%# distance from the goal~%float64 distance_from_goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LineTrackerFeedback)))
  "Returns full string definition for message of type 'LineTrackerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%# distance from the goal~%float64 distance_from_goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LineTrackerFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LineTrackerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LineTrackerFeedback
    (cl:cons ':distance_from_goal (distance_from_goal msg))
))
