; Auto-generated. Do not edit!


(cl:in-package kr_tracker_msgs-msg)


;//! \htmlinclude LissajousAdderActionGoal.msg.html

(cl:defclass <LissajousAdderActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type kr_tracker_msgs-msg:LissajousAdderGoal
    :initform (cl:make-instance 'kr_tracker_msgs-msg:LissajousAdderGoal)))
)

(cl:defclass LissajousAdderActionGoal (<LissajousAdderActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LissajousAdderActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LissajousAdderActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kr_tracker_msgs-msg:<LissajousAdderActionGoal> is deprecated: use kr_tracker_msgs-msg:LissajousAdderActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <LissajousAdderActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kr_tracker_msgs-msg:header-val is deprecated.  Use kr_tracker_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <LissajousAdderActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kr_tracker_msgs-msg:goal_id-val is deprecated.  Use kr_tracker_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <LissajousAdderActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kr_tracker_msgs-msg:goal-val is deprecated.  Use kr_tracker_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LissajousAdderActionGoal>) ostream)
  "Serializes a message object of type '<LissajousAdderActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LissajousAdderActionGoal>) istream)
  "Deserializes a message object of type '<LissajousAdderActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LissajousAdderActionGoal>)))
  "Returns string type for a message object of type '<LissajousAdderActionGoal>"
  "kr_tracker_msgs/LissajousAdderActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LissajousAdderActionGoal)))
  "Returns string type for a message object of type 'LissajousAdderActionGoal"
  "kr_tracker_msgs/LissajousAdderActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LissajousAdderActionGoal>)))
  "Returns md5sum for a message object of type '<LissajousAdderActionGoal>"
  "9dabc3f5020bdc8b5f13e716bd996b9f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LissajousAdderActionGoal)))
  "Returns md5sum for a message object of type 'LissajousAdderActionGoal"
  "9dabc3f5020bdc8b5f13e716bd996b9f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LissajousAdderActionGoal>)))
  "Returns full string definition for message of type '<LissajousAdderActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%LissajousAdderGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: kr_tracker_msgs/LissajousAdderGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float64[2] x_amp~%float64[2] y_amp~%float64[2] z_amp~%float64[2] yaw_amp~%float64[2] x_num_periods~%float64[2] y_num_periods~%float64[2] z_num_periods~%float64[2] yaw_num_periods~%float64[2] period~%float64[2] num_cycles~%float64[2] ramp_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LissajousAdderActionGoal)))
  "Returns full string definition for message of type 'LissajousAdderActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%LissajousAdderGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: kr_tracker_msgs/LissajousAdderGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float64[2] x_amp~%float64[2] y_amp~%float64[2] z_amp~%float64[2] yaw_amp~%float64[2] x_num_periods~%float64[2] y_num_periods~%float64[2] z_num_periods~%float64[2] yaw_num_periods~%float64[2] period~%float64[2] num_cycles~%float64[2] ramp_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LissajousAdderActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LissajousAdderActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LissajousAdderActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
