# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kr_tracker_msgs/PolyTrackerActionGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import actionlib_msgs.msg
import genpy
import geometry_msgs.msg
import kr_tracker_msgs.msg
import std_msgs.msg

class PolyTrackerActionGoal(genpy.Message):
  _md5sum = "bcb18c2c2b212492727a2c9eff70b279"
  _type = "kr_tracker_msgs/PolyTrackerActionGoal"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
PolyTrackerGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: kr_tracker_msgs/PolyTrackerGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
time t_start
uint8 order
bool set_yaw
bool separate_yaw
float64 start_yaw
float64 final_yaw
kr_tracker_msgs/Polynomial[] seg_x
kr_tracker_msgs/Polynomial[] seg_y
kr_tracker_msgs/Polynomial[] seg_z
kr_tracker_msgs/Polynomial[] seg_yaw
int8 cpts_status # 0 is no valid cpts, 1 is berstein, 2 is bspline
geometry_msgs/Point[] pos_pts 
float64[] yaw_pts
float32[] knots

================================================================================
MSG: kr_tracker_msgs/Polynomial
# There should be 1 more coeffs than the degree
int32 degree
float32 dt
uint8 basis
float32[] coeffs
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','goal_id','goal']
  _slot_types = ['std_msgs/Header','actionlib_msgs/GoalID','kr_tracker_msgs/PolyTrackerGoal']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,goal_id,goal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PolyTrackerActionGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = kr_tracker_msgs.msg.PolyTrackerGoal()
    else:
      self.header = std_msgs.msg.Header()
      self.goal_id = actionlib_msgs.msg.GoalID()
      self.goal = kr_tracker_msgs.msg.PolyTrackerGoal()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs))
      _x = self.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I3B2d().pack(_x.goal.t_start.secs, _x.goal.t_start.nsecs, _x.goal.order, _x.goal.set_yaw, _x.goal.separate_yaw, _x.goal.start_yaw, _x.goal.final_yaw))
      length = len(self.goal.seg_x)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_x:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.coeffs))
      length = len(self.goal.seg_y)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_y:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.coeffs))
      length = len(self.goal.seg_z)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_z:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.coeffs))
      length = len(self.goal.seg_yaw)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_yaw:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.coeffs))
      _x = self.goal.cpts_status
      buff.write(_get_struct_b().pack(_x))
      length = len(self.goal.pos_pts)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.pos_pts:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.goal.yaw_pts)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.goal.yaw_pts))
      length = len(self.goal.knots)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.goal.knots))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = kr_tracker_msgs.msg.PolyTrackerGoal()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.goal.t_start.secs, _x.goal.t_start.nsecs, _x.goal.order, _x.goal.set_yaw, _x.goal.separate_yaw, _x.goal.start_yaw, _x.goal.final_yaw,) = _get_struct_2I3B2d().unpack(str[start:end])
      self.goal.set_yaw = bool(self.goal.set_yaw)
      self.goal.separate_yaw = bool(self.goal.separate_yaw)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_x = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = s.unpack(str[start:end])
        self.goal.seg_x.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_y = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = s.unpack(str[start:end])
        self.goal.seg_y.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_z = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = s.unpack(str[start:end])
        self.goal.seg_z.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_yaw = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = s.unpack(str[start:end])
        self.goal.seg_yaw.append(val1)
      start = end
      end += 1
      (self.goal.cpts_status,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.pos_pts = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.goal.pos_pts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal.yaw_pts = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal.knots = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs))
      _x = self.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I3B2d().pack(_x.goal.t_start.secs, _x.goal.t_start.nsecs, _x.goal.order, _x.goal.set_yaw, _x.goal.separate_yaw, _x.goal.start_yaw, _x.goal.final_yaw))
      length = len(self.goal.seg_x)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_x:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.coeffs.tostring())
      length = len(self.goal.seg_y)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_y:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.coeffs.tostring())
      length = len(self.goal.seg_z)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_z:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.coeffs.tostring())
      length = len(self.goal.seg_yaw)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.seg_yaw:
        _x = val1
        buff.write(_get_struct_ifB().pack(_x.degree, _x.dt, _x.basis))
        length = len(val1.coeffs)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.coeffs.tostring())
      _x = self.goal.cpts_status
      buff.write(_get_struct_b().pack(_x))
      length = len(self.goal.pos_pts)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.pos_pts:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.goal.yaw_pts)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.goal.yaw_pts.tostring())
      length = len(self.goal.knots)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.goal.knots.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = kr_tracker_msgs.msg.PolyTrackerGoal()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.goal.t_start.secs, _x.goal.t_start.nsecs, _x.goal.order, _x.goal.set_yaw, _x.goal.separate_yaw, _x.goal.start_yaw, _x.goal.final_yaw,) = _get_struct_2I3B2d().unpack(str[start:end])
      self.goal.set_yaw = bool(self.goal.set_yaw)
      self.goal.separate_yaw = bool(self.goal.separate_yaw)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_x = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        self.goal.seg_x.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_y = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        self.goal.seg_y.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_z = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        self.goal.seg_z.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.seg_yaw = []
      for i in range(0, length):
        val1 = kr_tracker_msgs.msg.Polynomial()
        _x = val1
        start = end
        end += 9
        (_x.degree, _x.dt, _x.basis,) = _get_struct_ifB().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.coeffs = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        self.goal.seg_yaw.append(val1)
      start = end
      end += 1
      (self.goal.cpts_status,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.pos_pts = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.goal.pos_pts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal.yaw_pts = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal.knots = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2I3B2d = None
def _get_struct_2I3B2d():
    global _struct_2I3B2d
    if _struct_2I3B2d is None:
        _struct_2I3B2d = struct.Struct("<2I3B2d")
    return _struct_2I3B2d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
_struct_ifB = None
def _get_struct_ifB():
    global _struct_ifB
    if _struct_ifB is None:
        _struct_ifB = struct.Struct("<ifB")
    return _struct_ifB
